// Base de datos simulada de productos
export const products = [
  {
    id: 1,
    codigo: "ARR001",
    nombre: "Arroz Blanco 1kg",
    precio: 25.5,
    stock: 45,
    categoria: "Granos",
    proveedor: "Distribuidora Central",
    icon: "🍚",
  },
  {
    id: 2,
    codigo: "FRI001",
    nombre: "Frijol Negro 1kg",
    precio: 32.0,
    stock: 38,
    categoria: "Granos",
    proveedor: "Distribuidora Central",
    icon: "🫘",
  },
  {
    id: 3,
    codigo: "ACE001",
    nombre: "Aceite Vegetal 1L",
    precio: 45.0,
    stock: 22,
    categoria: "Aceites",
    proveedor: "Aceites del Sur",
    icon: "🫗",
  },
  {
    id: 4,
    codigo: "AZU001",
    nombre: "Azúcar Refinada 1kg",
    precio: 28.0,
    stock: 50,
    categoria: "Endulzantes",
    proveedor: "Distribuidora Central",
    icon: "🧂",
  },
  {
    id: 5,
    codigo: "SAL001",
    nombre: "Sal de Mesa 1kg",
    precio: 12.0,
    stock: 60,
    categoria: "Condimentos",
    proveedor: "Sal Marina",
    icon: "🧂",
  },
  {
    id: 6,
    codigo: "PAS001",
    nombre: "Pasta Espagueti 500g",
    precio: 18.5,
    stock: 35,
    categoria: "Pastas",
    proveedor: "Pastas Italianas",
    icon: "🍝",
  },
  {
    id: 7,
    codigo: "LEH001",
    nombre: "Leche Entera 1L",
    precio: 22.0,
    stock: 8,
    categoria: "Lácteos",
    proveedor: "Lácteos Frescos",
    icon: "🥛",
  },
  {
    id: 8,
    codigo: "HUE001",
    nombre: "Huevos Blancos 12pz",
    precio: 48.0,
    stock: 15,
    categoria: "Huevos",
    proveedor: "Granja Feliz",
    icon: "🥚",
  },
  {
    id: 9,
    codigo: "PAN001",
    nombre: "Pan de Caja Integral",
    precio: 35.0,
    stock: 12,
    categoria: "Panadería",
    proveedor: "Panadería Moderna",
    icon: "🍞",
  },
  {
    id: 10,
    codigo: "JAB001",
    nombre: "Jabón de Tocador 3pz",
    precio: 28.0,
    stock: 25,
    categoria: "Higiene",
    proveedor: "Productos de Limpieza",
    icon: "🧼",
  },
  {
    id: 11,
    codigo: "PAP001",
    nombre: "Papel Higiénico 4 rollos",
    precio: 42.0,
    stock: 18,
    categoria: "Higiene",
    proveedor: "Productos de Limpieza",
    icon: "🧻",
  },
  {
    id: 12,
    codigo: "ATO001",
    nombre: "Atún en Lata 140g",
    precio: 16.5,
    stock: 40,
    categoria: "Enlatados",
    proveedor: "Conservas del Mar",
    icon: "🥫",
  },
  {
    id: 13,
    codigo: "REF001",
    nombre: "Refresco Cola 2L",
    precio: 28.0,
    stock: 30,
    categoria: "Bebidas",
    proveedor: "Bebidas Refrescantes",
    icon: "🥤",
  },
  {
    id: 14,
    codigo: "GAL001",
    nombre: "Galletas Saladas 200g",
    precio: 22.0,
    stock: 5,
    categoria: "Botanas",
    proveedor: "Galletas y Más",
    icon: "🍪",
  },
  {
    id: 15,
    codigo: "CHO001",
    nombre: "Chocolate en Polvo 400g",
    precio: 55.0,
    stock: 20,
    categoria: "Bebidas",
    proveedor: "Chocolates Premium",
    icon: "🍫",
  },
]

export function getProducts() {
  return products
}

export function getProductById(id) {
  return products.find((p) => p.id === id)
}
